apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-consumer-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scanner-job-creator
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanner-consumer-job-creator
  namespace: default
subjects:
- kind: ServiceAccount
  name: scanner-consumer-sa
  namespace: default
roleRef:
  kind: Role
  name: scanner-job-creator
  apiGroup: rbac.authorization.k8s.io 